title: 김태영
# email: tyhjgood@naver.com
description: >
baseurl: ""
url: "http://tae-young.github.io"
github_username: tae-young
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
